services:
    _defaults:
        autowire: true
        autoconfigure: true

    export_toolkit.logger:
        alias: monolog.logger.export_toolkit

    exporttoolkit.event_listener:
        class: Elements\Bundle\ExportToolkitBundle\EventListener\ExportListener
        arguments:
            - "@exporttoolkit.exportservice"
        tags:
            - { name: kernel.event_subscriber }

    exporttoolkit.exportservice:
        class: Elements\Bundle\ExportToolkitBundle\ExportService
        lazy: true
        calls:
            - [setLogger, ['@export_toolkit.logger']]

    Elements\Bundle\ExportToolkitBundle\ExportService:
        alias: "exporttoolkit.exportservice"

    Elements\Bundle\ExportToolkitBundle\Command\:
        resource: '../../Command'
        arguments:
            $exportService: '@exporttoolkit.exportservice'

    Elements\Bundle\ExportToolkitBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

